#!usr/bin/php
<?php
/*************************************************
 * TheYkk's fw
 * Framework console
 *
 * Author 	: Yusuf Kaan Karakaya
 * Web 		: http://theykk.net
 *
 * Version 	: 2.2.0
 * Github	: http://github.com/theykk/fw
 * License	: MIT
 *
 *************************************************/
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/System/Kernel/Starter.php';

$params     = array_slice($argv, 1);
$console    = new System\Libs\Console\Console();

echo $console->run($params);
